name: tomcat-sandbox
services:
  tomcat:
    image: tomcat:11.0
    container_name: tomcat-server
    ports:
      - '80:8080'
    volumes:
      - ./rest-spring.war:/usr/local/tomcat/webapps/rest-spring.war
      - ./exchange:/usr/local/tomcat/exchange

