name: tomcat-sandbox
services:
  tomcat:
    image: tomcat:11.0
    container_name: tomcat-server
    hostname: tomcat-host
    ports:
      - '80:8080'
    volumes:
      - ./rest-spring.war:/usr/local/tomcat/webapps/rest-spring.war
      - ./_exchange:/usr/local/tomcat/exchange
      - ./logs:/usr/local/tomcat/logs
    environment:
      - SPRING_PROFILES_ACTIVE=dev
