spring:
  jackson:
    # non 'null' and empty ""
    DEFAULT_PROPERTY_INCLUSION: NON_EMPTY
    DATE_FORMAT: yyyy-MM-dd HH:mm:ss
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

  web:
    resources:
      static-locations: file:/rest-spring/images

management:
  endpoints:
    web:
      exposure:
        include: "*"
      security:
        enabled: false
      health:
        sensitive: true
        show-details: "always"

server:
  servlet.context-path: "/rest-spring"
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
